class Course:
    def __init__(self, title: str, code: str, url: str, table_url: str):
        self.title = title
        self.code = code
        self.url = url
        self.table_url = table_url


course_list = [
Course("Актер", "52.05.01", "https://www.hse.ru/ba/actor/",
    "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Akter_O.xlsx"),
Course("Ассириология: языки и история древней Месопотамии", "58.03.01", "https://www.hse.ru/ba/assyriology/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Assir_O.xlsx"),
Course("Бизнес-информатика", "38.03.05", "https://www.hse.ru/ba/bi/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_BI_O.xlsx"),
Course("Востоковедение", "58.03.01", "https://www.hse.ru/ba/oriental/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Vostok_O.xlsx"),
Course("География глобальных изменений и геоинформационные технологии", "05.03.02", "https://www.hse.ru/ba/geography/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_GGIGT_O.xlsx"),
Course("Городское планирование", "07.03.04", "https://www.hse.ru/ba/up/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_GorPlan_O.xlsx"),
Course("Государственное и муниципальное управление", "38.03.04", "https://www.hse.ru/ba/gmu/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_GMU_O.xlsx"),
Course("Дизайн", "54.03.01", "https://design.hse.ru/ba/program/design",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Design_O.xlsx"),
Course("Дизайн и разработка информационных продуктов", "09.03.04", "https://www.hse.ru/ba/drip/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_DisDevInfP_O.xlsx"),
Course("Журналистика", "42.03.02", "https://www.hse.ru/ba/journ/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_ZHur_O.xlsx"),
Course("Иностранные языки и межкультурная коммуникация", "45.03.02", "https://www.hse.ru/ba/lang/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_IYAMK_O.xlsx"),
Course("Инфокоммуникационные технологии и системы связи", "11.03.02", "https://www.hse.ru/ba/it/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_ITSS_O.xlsx"),
Course("Информатика и вычислительная техника", "09.03.01", "https://www.hse.ru/ba/isct/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_IVT_O.xlsx"),
Course("Информационная безопасность", "10.03.01", "https://www.hse.ru/ba/is/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_IB_O.xlsx"),
Course("История", "46.03.01", "https://www.hse.ru/ba/hist/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_ISTR_O.xlsx"),
Course("История искусств", "50.03.03", "https://www.hse.ru/ba/histart/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Isk_O.xlsx"),
Course("Кинопроизводство", "42.03.05", "https://www.hse.ru/ba/film/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Film_O.xlsx"),
Course("Клеточная и молекулярная биотехнология", "06.03.01", "https://www.hse.ru/ba/cmb/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_CMB_O.xlsx"),
Course("Когнитивная нейробиология", "06.03.01", "https://www.hse.ru/ba/neuroscience/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_KogNeir_O.xlsx"),
Course("Компьютерная безопасность", "10.05.01", "https://www.hse.ru/ba/cosec/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_KB_O.xlsx"),
Course("Компьютерные науки и анализ данных", "01.03.02", "https://www.hse.ru/ba/compds/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Compds_O.xlsx"),
Course("Культурология", "51.03.01", "https://www.hse.ru/ba/cultural/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Cultural_O.xlsx"),
Course("Маркетинг и рыночная аналитика", "38.03.02", "https://www.hse.ru/ba/marketing/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Marketing_O.xlsx"),
Course("Математика", "01.03.01", "https://www.hse.ru/ba/math/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Math_O.xlsx"),
Course("Медиакоммуникации", "42.03.05", "https://www.hse.ru/ba/media/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Media_O.xlsx"),
Course("Международная программа по экономике и финансам", "38.03.01", "https://www.hse.ru/ba/icef/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_icef_O.xlsx"),
Course("Международные отношения", "41.03.05", "https://www.hse.ru/ba/ia/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_MO_O.xlsx"),
Course("Международный бизнес", "38.03.02", "https://www.hse.ru/ba/ib/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_MB_O.xlsx"),
Course("Мировая экономика", "38.03.01", "https://www.hse.ru/ba/we/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_WE_O.xlsx"),
Course("Мода", "54.03.01", "https://design.hse.ru/ba/program/fashion",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Moda_O.xlsx"),
Course("Политология", "41.03.04", "https://www.hse.ru/ba/political/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Political_O.xlsx"),
Course("Прикладная математика", "01.03.04", "https://www.hse.ru/ba/am/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_AM_O.xlsx"),
Course("Прикладная математика и информатика", "01.03.02", "https://www.hse.ru/ba/ami/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_AMI_O.xlsx"),
Course("Прикладной анализ данных", "01.03.02", "https://www.hse.ru/ba/data/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Data_O.xlsx"),
Course("Программная инженерия", "09.03.04", "https://www.hse.ru/ba/se/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_SE_O.xlsx"),
Course("Психология", "37.03.01", "https://www.hse.ru/ba/psy/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Psy_O.xlsx"),
Course("Реклама и связи с общественностью", "42.03.05", "https://www.hse.ru/ba/ad/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_AD_O.xlsx"),
Course("Совместная программа по экономике НИУ ВШЭ и РЭШ", "38.03.01", "https://www.hse.ru/ba/nes/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_RESH_O.xlsx"),
Course("Современное искусство", "50.03.02", "https://art.hse.ru/ba",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Art_O.xlsx"),
Course("Социология", "39.03.01", "https://www.hse.ru/ba/soc/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Soc_O.xlsx"),
Course("Стратегия и продюсирование в коммуникациях", "42.03.01", "https://www.hse.ru/ba/producer/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Producer_O.xlsx"),
Course("Управление бизнесом", "38.03.02", "https://www.hse.ru/ba/bba/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_BBA_O.xlsx"),
Course("Управление в креативных индустриях", "42.03.05", "https://creative.hse.ru/ba",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Creative_O.xlsx"),
Course("Управление цепями поставок и бизнес-аналитика", "38.03.02", "https://www.hse.ru/ba/logistics/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Logistics_O.xlsx"),
Course("Управление цифровым продуктом", "38.03.05", "https://www.hse.ru/ba/digital/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Digital_O.xlsx"),
Course("Физика", "03.03.02", "https://www.hse.ru/ba/physics/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Physics_O.xlsx"),
Course("Филология", "45.03.01", "https://www.hse.ru/ba/philology/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Philology_O.xlsx"),
Course("Философия", "47.03.01", "https://www.hse.ru/ba/phil/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Phil_O.xlsx"),
Course("Фундаментальная и компьютерная лингвистика", "45.03.03", "https://www.hse.ru/ba/ling/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_FKL_O.xlsx"),
Course("Химия", "04.03.01", "https://www.hse.ru/ba/chem/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Chem_O.xlsx"),
Course("Экономика", "38.03.01", "https://www.hse.ru/ba/economics/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Economy_O.xlsx"),
Course("Экономика и анализ данных", "38.03.01", "https://www.hse.ru/ba/eda/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_EcAl_O.xlsx"),
Course("Экономика и статистика", "38.03.01", "https://www.hse.ru/ba/stat/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Stat_O.xlsx"),
Course("Экономический анализ", "38.03.01", "https://www.hse.ru/ba/ea/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_EA_O.xlsx"),
Course("Юго-Восточная Азия: языки, история, культуры", "58.03.01", "https://www.hse.ru/ba/asia/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Asia_O.xlsx"),
Course("Юриспруденция", "40.03.01", "https://www.hse.ru/ba/law/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_LAW_O.xlsx"),
Course("Юриспруденция: цифровой юрист", "40.03.01", "https://www.hse.ru/ba/dlawyer/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Dlawyer_O.xlsx"),
Course("Япония: язык, история, литература, культура", "58.03.01", "https://www.hse.ru/ba/japanese/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Japanese_O.xlsx"),
Course("Античность (История)", "46.03.01", "https://www.hse.ru/ba/antiq/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Ant_Ist_O.xlsx"),
Course("Античность (Филология)", "45.03.01", "https://www.hse.ru/ba/antiq/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Ant_Fil_O.xlsx"),
Course("Глобальные цифровые коммуникации (Медиакоммуникации)", "42.03.05", "https://www.hse.ru/ba/digitalcomm/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_GlDComM_O.xlsx"),
Course("Глобальные цифровые коммуникации (Реклама и связи с общественностью)", "42.03.01", "https://www.hse.ru/ba/digitalcomm/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_GlDCom_O.xlsx"),
Course("Международная программа «Международные отношения и глобальные исследования» (Международные отношения)", "41.03.05", "https://www.hse.ru/ba/ir/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_irmo_O.xlsx"),
Course("Международная программа «Международные отношения и глобальные исследования» (Публичная политика и социальные науки)", "41.03.06", "https://www.hse.ru/ba/ir/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_irpp_O.xlsx"),
Course('Программа двух дипломов НИУ ВШЭ и Университета Кёнхи «Экономика и политика Азии» (Зарубежное регионоведение)', "41.03.01", "https://www.hse.ru/ba/epa/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_epa27_O.xlsx"),
Course("Программа двух дипломов НИУ ВШЭ и Университета Кёнхи «Экономика и политика Азии» (Публичная политика и социальные науки)", "41.03.06", "https://www.hse.ru/ba/epa/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_epa29_O.xlsx"),
Course("Реклама и связи с общественностью (Медиакоммуникации)", "42.03.05", "https://www.hse.ru/ba/ad/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_ADM_O.xlsx"),
Course("Совместный бакалавриат НИУ ВШЭ и Центра педагогического мастерства", "01.03.01", "https://www.hse.ru/ba/cpm/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_CPM_O.xlsx"),
Course("Юриспруденция: правовое регулирование бизнеса", "40.03.01", "https://pravo.hse.ru/doplaw/",
       "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/BD_moscow_Doplaw_OZ.xlsx"),
]

stats_url = "https://enrol.hse.ru/storage/public_report_2024/moscow/Bachelors/ReportRectorMoscowBachelors2024.xlsx"

course_ord = ["Математика","Совместный бакалавриат НИУ ВШЭ и Центра педагогического мастерства","Компьютерные науки и анализ данных","Прикладная математика и информатика","Прикладной анализ данных","Прикладная математика","Физика","Химия","География глобальных изменений и геоинформационные технологии","Клеточная и молекулярная биотехнология","Когнитивная нейробиология","Городское планирование","Информатика и вычислительная техника","Дизайн и разработка информационных продуктов","Программная инженерия","Информационная безопасность","Компьютерная безопасность","Инфокоммуникационные технологии и системы связи","Психология","Международная программа по экономике и финансам","Мировая экономика","Совместная программа по экономике НИУ ВШЭ и РЭШ","Экономика","Экономика и анализ данных","Экономика и статистика","Экономический анализ","Маркетинг и рыночная аналитика","Международный бизнес","Управление бизнесом","Управление цепями поставок и бизнес-аналитика","Государственное и муниципальное управление","Бизнес-информатика","Управление цифровым продуктом","Социология","Юриспруденция","Юриспруденция: правовое регулирование бизнеса","Юриспруденция: цифровой юрист","Программа двух дипломов НИУ ВШЭ и Университета Кёнхи «Экономика и политика Азии» (Зарубежное регионоведение)","Политология","Международная программа «Международные отношения и глобальные исследования» (Международные отношения)","Международные отношения","Международная программа «Международные отношения и глобальные исследования» (Публичная политика и социальные науки)","Программа двух дипломов НИУ ВШЭ и Университета Кёнхи «Экономика и политика Азии» (Публичная политика и социальные науки)","Глобальные цифровые коммуникации (Реклама и связи с общественностью)","Реклама и связи с общественностью","Стратегия и продюсирование в коммуникациях","Журналистика","Глобальные цифровые коммуникации (Медиакоммуникации)","Кинопроизводство","Медиакоммуникации","Реклама и связи с общественностью (Медиакоммуникации)","Управление в креативных индустриях","Античность (Филология)","Филология","Иностранные языки и межкультурная коммуникация","Фундаментальная и компьютерная лингвистика","Античность (История)","История","Философия","Современное искусство","История искусств","Культурология","Актер","Дизайн","Мода","Ассириология: языки и история древней Месопотамии","Востоковедение","Юго-Восточная Азия: языки, история, культуры","Япония: язык, история, литература, культура"]